// <auto-generated />
namespace ImcLabApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class editTestFieldNameUrlName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editTestFieldNameUrlName));
        
        string IMigrationMetadata.Id
        {
            get { return "201909191519342_editTestFieldNameUrlName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
